model_name: "pixart_sigma_ugile"
model_id:   "futurefrompast/pixart-alpha-512"

device: "cuda"
seed:   41
seeds: [41, 42, 43, 44, 45]

prompts:
  - "a photo of an astronaut riding a horse on mars"
  - "A woman holding a purple umbrella walking in the rain"
  - "A view of a multi-tiered clock tower with an American flag on the top."
  - "a sink and a mirror reflecting the many pictures on the wall"
  - "A man in a kitchen instructing a woman on what to do"
  - "there are two cups in front of the bathroom mirror"
  - "A kitchen that appears to be missing a cabinet door"
  - "Spoon in a bowl of chopped vegetables with butter"
  - "A large Sonic statue on a beach next to a surf board."
  - "A vintage wood stove used for cooking or baking."
  - "A sepia photo of Big Ben in London, seen from below"
  - "A kite flying through a blue sky with a long tail"
  - "A small dog is sticking its head out of a backpack"
  - "A pasta dish with mushrooms and broccoli in a cream sauce"
  - "a person is skiing down a snowy slope"
  - "A vintage closeup shows a chair with a toddler with a big smile and a big toy bear seated right next to a second toddler with a semi-smile, holding what appears to be a coin purse"
  - "Two small frying pans have eggs and a slice of ham on a stove"
  - "A little girl in a rocking chair holding a teddy bear"
  - "Lemons, apples, and a coffee cup in an arranged 'still life'."
  - "a yellow food truck parked on the side of a city street"
  - "Pizza type meal set out on a wooden table with plates."
  - "the corner of a bathroom with light mint green walls above the tile."
  - "A cat snuggled up to a pair of shoes on the floor."
  - "a pasta dish with colorful vegtables on white plate"
  - "A blue and white VW bus driving down a street."
  - "A counter topped with bowls of food and a cutting board."
  - "A midsized plant with leaves of varying colors"
  - "A black handled toothbrush with new bristles on it."
  - "A paddle boarder on a large, still body of water."
  - "The dog is laying down on the couch in the room."
  - "A table that is in the middle of a living room."
  # - "A bathroom with two sinks and a toilet."
  # - "A bathroom door is opened by a toilet."
  # - "A large sign that says cave next to a sign that says resturant and lounge."
  # - "A bathroom sink under a mirror next to a plant."
  # - "A table topped with glasses of wine half full."
  # - "A keyboard and mouse in front of a computer."
  # - "A group of people standing outside of a building."
  # - "a stuffed animal on a table near a drink"
  # - "three zebras eating grass in a field near a tree"
  # - "A stop sign tipped over and buried in the snow"
  # - "A dog that is laying down next to a teddy bear."
  # - "The group is going skiing on the snow."
  # - "A bathroom with walk-in shower, deep tub and sink overlooks other townhouses"
  # - "One picture has a couch and a coffee table, one has a bicycle, another has a two desks with chairs, and the largest picture has a kitchen bar and shelves with various items."
  # - "street lights showing red and yellow near a bike lane"
  # - "The red brick building has a clock tower in the middle."
  # - "Modern living room with two chairs, a three bay window and fireplace."
  # - "Living room that includes television, chair and multiple windows."
  # - "A white table topped with a bottle of champagne and two glasses with a plate."
  # - "A surf boarder walks out of the water"
  # - "Tho city buses on a street, one with its engine showing."
  # - "a public transit bus on a city street"
  # - "A place flies over the water that reflects the sunset light."
  # - "ALL YOU SEE IS A LOT OF LEGS AND ALOT OF SNOW BOARDS"
  # - "a big yellow school bus parked in front of some trees."
  # - "A bathroom showing sink, toilet, and shower"
  # - "A white and red bus on a street"
  # - "A motorcycle that is parked on the side of the road."
  # - "A room with a glass coffe table and a couch and chair."
  # - "A building is lit up on the corner of a street."
  # - "A kitchen with wooden cabinets and various bowls of fruits and vegetables on the counter, next to a white stovetop oven."
  # - "Two clay pots with leafy green plants in them."
  # - "A red train crossing over a white bridge,"
  # - "a bathroom with a striped bathroom curtain"
  # - "A single rainbow is seen between a building and a road sign."
  # - "A large flock of sheep block the road in front of a bus."
  # - "A close up of a pile of paper clips on a home office desk."
  # - "A walkway suspended over a street with a clock mounted to it."
  # - "a boat in the water with a city skyline behind it"
  # - "A view of a vase with purple flowers in it."
  # - "Two stuffed bears seated at a table for a meal."
  # - "carrots, broccoli, and cauliflower on a plate"
  # - "a line of bikes that are next to the road"
  # - "A bathroom with a sink and television inside of the mirror."
  # - "A plate that has some broccoli on it."
  # - "an image of a stop sign that is on the gate"
  # - "A plate with a cupcake on top of it next to an orange."
  # - "A wall cutting through a large hill by the water."
  # - "a living room with a couch chairs a table and a tv"
  # - "A bowl of pizza, a bowl of green beans, a bowl of carrots, and a bowl of bread and berries."
  # - "A shuttle bus rides along a curved street."
  # - "A train that is on a track next to the trees."
  # - "Various stuffed animals behind a pane of glass"
  # - "A dog going to the bathroom in the park."
  # - "The three clear vases each have flowers in them."
  # - "A plate topped with a cheesy pizza on a table."
  # - "The tree branches behind the tower clock lend style to it."
  # - "A close up of what appears to be two traffic machines."
  # - "a bathroom with a bath tub a sink and a mirror"
  # - "a plate of pizza next to a bag of grapes on a plate"
  # - "A picture of a lone clock tower standing in a school yard."
  # - "A computer desk with a row of books underneath it"
  # - "some vases on two tables with green and white flowers in them"
  # - "A snow boarded stops to pose for a picture."
  # - "A tall building with balconies behind a red and white sign."
  # - "A cartoon covered truck parks in front of a city building."
  # - "Two cross country skiing competitors ski on a tree-lined course."
  # - "A large three layer happy birthday cake on a plate.."
  # - "a room well arranged and a vase of flowers"
  # - "A bus that is on the side of the road."
  # - "A glass of drink and a plate of food on a table."
  # - "A horse alks along a chain linked fence in the grass."
  # - "A catcher that is reacting to a pitch he just caught."
  # - "A bathroom that has raised sinks with a black counter top."
  # - "A cat laying on top of a basket on a table with a mirror above it"
  # - "Plate of food resting in front of keyboard on the desk"
  # - "A bird perched on top of a leafless tree under a blue sky."
  # - "The Big Ben clock tower towering over the city of London."
  # - "The bathroom is clean and ready to use."
  # - "Broccoli and beef pizza on a plate for a meal."
  # - "a cat is laying on a table near a laptop and papers"
  # - "A dog leaping in the air to grab a frisbee from its owner on a snowy day."
  # - "Several desserts on white plates near a glass of wine."
  # - "a close up of a cat in a cat bed with a teddy bear"
  # - "Bathroom scene with white background and tan accents."
  # - "Two horses are eating grass in a field."
  # - "A bathroom with porcelain toilet and a mirrored wall."
  # - "A tree in bloom with pink flowers near a rural area."
  # - "Cows crossing a country road behind a large truck."
  # - "a snowboarded catching air jumping off a slope"
  # - "A bunch of hot dogs in a bowl with beer being poured on them"
  # - "A bathroom with a toilet and a scale on the floor."
  # - "A pink flower inside a water vase with some lights shining unto."
  # - "A kitten drinking water out of a bowl on a tray."
  # - "A picture of a little house and some grass."
  # - "Cather preparing to catch ball in an empty field"
  # - "A red trolly bus driving down a dirt road."
  # - "A mostly white kitchen has dishes in the sink."
  # - "There is a living room with chairs in it"
  # - "A street with various market vendors and an umbrella."
  # - "There are a bunch of dead flowers in this vase."
  # - "a train that is on a train train track"
  # - "Picture of a three piece bathroom that is all white and beige."
  # - "a rome with rose flowers and a sink"
  # - "A toilet and toilet paper roll sit in a partially constructed bathroom."
  # - "A laptop next to a host of bowls with vegetables and a loaf of bread."
  # - "a public bathroom with several sinks and mirrors"
  # - "Kitchen of home with electric stove and wood oven."
  # - "A picnic table under an awning and wooden potted plants."
  # - "A bench in front of a bookshelf, filled with books near a table and window."
  # - "A bathroom with a shower curtain, toilet and a sink."
  # - "A cat laying on a wooden table under a umbrella."
  # - "A bus on the street with a lot of cars."
  # - "A bird setting on the back of a park bench with trees in the background."
  # - "Dark dingy bathroom with a full white tub."
  # - "Three bridge supports upright in a trickling creek."
  # - "a church sits on a busy corner street"
  # - "A corner of an empty city street with cars parked on the road."
  # - "A train traveling down train tracks next to a tall building."
  # - "A group of people who are outside of a building."
  # - "this clean bathroom has all white fixtures in it"
  # - "A steak and vegetable meal on a plate."
  # - "Doughnuts in a box are on a counter for sale."
  # - "Two sinks side by side inside a clean public bathroom"
  # - "A stop sign that has some graffiti on it."
  # - "A park bench with a backpack on it in a forest of trees."
  # - "A normal bench sitting on a wooden bridge"
  # - "A white toilet in a bathroom next to a trash can.;"
  # - "A bathroom with a bathtub next to a white toilet and a sink."
  # - "A train engine carrying carts down a track to a station."
  # - "Plates of chicken and vegetable, a plate with bread and a bowl of soup."
  # - "A clock tower with a blue sky is pictured."
  # - "a yellow and blue train engine is pulling its train cars and tracks"
  # - "A stop sign stands along a snow filled street."
  # - "A street sign hangs in front of a large building."
  # - "A bed decorated with towels folded into heart shapes."
  # - "A bathroom is shown with a toilet, sink and bathtub."
  # - "A black and white picture of two shoes on a board"
  # - "A corner of a street next to a building"
  # - "A lone bird soaring into the sky filled with clouds."
  # - "A bathroom has brown towels and counter top."
  # - "Young puppy in bathroom tearing up much toilet paper"
  # - "A toilet that is in a very nice bathroom."
  # - "A flock of birds flying over water and sand with a volley ball net on the sand."
  # - "in this photo you can see many buildings and a tall tower with a clock"
  # - "Cars parked on the side of the street and traveling down the road"
  # - "There are numerous sea gulls flying near the ocean coast."
  # - "A herd of animals grazes in a field while a zebra nurses its foal."
  # - "A plate on a table that has food on it."
  # - "A white horse drawn carriage in front of a yellow building."
  # -  "Two shots of elephants near rocks and a fence."
  # - "A toddler boy is sitting on a brief case."
  # - "A group of elephants under a pavilion next to trees."
  # - "Horses are eating the grass in a field."
  # - "An elderly man prepares to eat a very large sundae."
  # - "an image of a man in a boat with a dog"
  # - "A herd of gray elephants standing next to each other on a block of cement."
  # - "An open book in front of a keyboard and monitor"
  # - "A cat that is standing on top of a laptop."
  # - "This girl is outside playing with an oven"
  # - "A wooden utility pole sports several street signs."
  # - "A slow motion picture of a pitcher pitching a game"
  # - "A picture of a bird on a rustic looking feeder"
  # - "Man wearing chef hat with bird on shoulder having a disaster in kitchen."
  # - "A pink stuffed animal on top of a cat in a cat bed."
  # - "a fire hydrant sits off a city street"
  # - "People walking and loitering around a train station clock and ticket machines"
  # - "A white plate topped with lots of different snacks."
  # - "Two horses are being fed by people eating at a table."
  # - "a couple of people sitting down staring at some people in the lake."

negative_prompt: ""

output: "prompt_pixart.png"

generation:
  height: 512
  width:  512

flow:
  num_steps:      50
  guidance_scale: 4

ugile:
  sigma_lo:     -1.0
  sigma_hi:     1.0
  theta_max:    1.2
  noise_scale:  5.5
  diverse_output_dir:  "outputs/diverse"
  original_output_dir: "outputs/original"
  save_original: true
