"""
Batch CADS inference script, designed to be launched by the dual-GPU
parallel-split script you provided (split_and_run_parallel_safe).

Usage (as called by the launcher):
    CUDA_VISIBLE_DEVICES=0 python inference.py --config config_gpu0.yaml
    CUDA_VISIBLE_DEVICES=1 python inference.py --config config_gpu1.yaml

Each per-GPU config.yaml (auto-generated by the launcher) contains:
    prompts_file : path to a YAML file with a top-level `prompts: [...]` list
                   (this GPU's shard only)
    prompt_offset: the GLOBAL index of this shard's first prompt, so that
                   output filenames stay correctly numbered across both GPUs
                   (e.g. GPU0 -> 0.png, 1.png, ...; GPU1 continues at midpoint.png ...)

All other keys (model / generation / cads / output) are identical to the
single-prompt config.yaml used by run.py — this script is a drop-in batch
version of the same CADS pipeline (cads.py / pipeline_cads.py are unchanged
and reused as-is).
"""

import os
import argparse
import yaml
import torch

from cads import CADSScheduleConfig
from pipeline_cads import CADSStableDiffusion, CADSGenerationConfig


def load_yaml(path: str) -> dict:
    with open(path, "r") as f:
        return yaml.safe_load(f)


def parse_prompts(prompts_data) -> list:
    if isinstance(prompts_data, list):
        return prompts_data
    if isinstance(prompts_data, dict):
        return prompts_data.get("prompts", [])
    return []


def clean_seed(raw_seed):
    """Robust against stray/malformed values (e.g. glued inline comments)."""
    if raw_seed is None:
        return None
    if isinstance(raw_seed, str):
        raw_seed = raw_seed.split("#")[0].strip()
    return int(raw_seed)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=str, required=True)
    args = parser.parse_args()

    cfg = load_yaml(args.config)

    # --- resolve this shard's prompts + global offset (set by the launcher) ---
    prompts_file = cfg.get("prompts_file")
    prompt_offset = int(cfg.get("prompt_offset", 0))

    if not prompts_file or not os.path.exists(prompts_file):
        raise FileNotFoundError(
            f"prompts_file '{prompts_file}' not found. The launcher must set "
            f"'prompts_file' in each per-GPU config."
        )
    prompts_data = load_yaml(prompts_file)
    prompts = parse_prompts(prompts_data)
    if not prompts:
        print(f"⚠️  No prompts found in {prompts_file}. Nothing to do on this GPU.")
        return

    device_tag = os.environ.get("CUDA_VISIBLE_DEVICES", "?")
    print(f"[GPU {device_tag}] {len(prompts)} prompts assigned, "
          f"global offset={prompt_offset}")

    # --- build model once, reuse across all prompts on this GPU ---
    dtype = torch.float16 if cfg["model"]["dtype"] == "float16" else torch.float32
    cads_cfg = CADSScheduleConfig(
        tau1=cfg["cads"]["tau1"],
        tau2=cfg["cads"]["tau2"],
        noise_scale=cfg["cads"]["noise_scale"],
        psi=cfg["cads"]["psi"],
        rescale=cfg["cads"]["rescale"],
        apply_to=cfg["cads"]["apply_to"],
    )
    print(f"[GPU {device_tag}] CADS config: {cads_cfg}")

    model = CADSStableDiffusion(
        model_id=cfg["model"]["model_id"],
        cads_config=cads_cfg,
        dtype=dtype,
    )

    gen_cfg = cfg["generation"]
    out_dir = cfg["output"]["output_dir"]
    os.makedirs(out_dir, exist_ok=True)

    base_seed = clean_seed(gen_cfg.get("seed", None))

    for local_i, prompt in enumerate(prompts):
        global_i = prompt_offset + local_i

        # Deterministic per-prompt seed offset by GLOBAL index, so GPU0/GPU1
        # never collide on the same seed and results stay reproducible
        # regardless of how the prompt list is split across GPUs.
        seed_i = None if base_seed is None else base_seed + global_i

        g = CADSGenerationConfig(
            prompt=prompt,
            negative_prompt=gen_cfg.get("negative_prompt", ""),
            num_inference_steps=gen_cfg.get("num_inference_steps", 50),
            guidance_scale=gen_cfg.get("guidance_scale", 9.0),
            height=gen_cfg.get("height", 768),
            width=gen_cfg.get("width", 768),
            seed=seed_i,
            use_cads=gen_cfg.get("use_cads", True),
        )

        print(f"[GPU {device_tag}] ({local_i+1}/{len(prompts)}, global#{global_i}) "
              f"seed={seed_i} :: \"{prompt}\"")

        image = model.generate(g)
        out_path = os.path.join(out_dir, f"{global_i}.png")
        image.save(out_path)
        print(f"[GPU {device_tag}] Saved: {out_path}")

    print(f"[GPU {device_tag}] ✅ Done — {len(prompts)} prompts rendered.")


if __name__ == "__main__":
    main()
